### ISSUE TITLE
Button search

### ISSUE THREAD

**Issue by kkseven07** [kenny-hibino/react-places-autocomplete#165]
How to trigger searching for place by button, not by selecting autocomplete suggestion?

**Comment by kenny-hibino** [comment]
@kkseven07 Could you explain this in detail? Example would be helpful 👍

**Comment by kkseven07** [comment]
I want to enter the address, click the button and get the coordinates if such address exists, if not - error. Are there any prop methods like this?

**Comment by CoVoCre** [comment]
Hey @kkseven07, maybe you could just set up your project so that it fills in the address of both with just one entry ? Like getting the address from the autocompleted component, and input it into the address of the shop !
That would mean using the geocodeByAdress function to get the address through a callback ! (See utility functions of readme ;) )

**Comment by kenny-hibino** [comment]
Thanks @CoVoCre! Hope this solution works for you @kkseven07 !!
